import type { Copy, Lang } from './types';

export const COPY: Record<Lang, Copy> = {
  en: {
    nav: ['Courses', 'How it works', 'Projects', 'Pricing'],
    cta: { book: 'Book a free class', demo: 'Watch demo' },
    hero: {
      pill1: 'New',
      pill2: 'AI track for teens',
      title: 'Where young minds build the',
      titleAccent: 'future',
      sub: 'Live, online coding & AI classes for ages 8–18 — taught with one-on-one guidance, so every child graduates owning a real project.',
      chips: ['Ages 8–18', 'Live online classes', 'Project-based'],
      floatNum: '1,000+',
      floatLabel: 'projects shipped by kids',
    },
    stats: [
      { v: '12k+', l: 'Young makers' },
      { v: '120+', l: 'Live courses' },
      { v: '98%', l: 'Parent satisfaction' },
      { v: '4.9★', l: 'Average rating' },
    ],
    courses: {
      eyebrow: 'Popular tracks',
      title: 'Courses kids actually finish',
      sub: 'Project-based tracks that turn screen time into building time.',
      filters: ['All', 'Coding', 'AI', 'Robotics'],
      cta: 'View course',
      items: [
        { title: 'Build Games with Scratch', blurb: 'Drag, drop and play — a first real game.', icon: 'gamepad-2', tone: 'orange', level: 'Beginner', levelColor: 'teal', age: '8–10', lessons: 12, cat: 'Coding' },
        { title: 'Python for Young Coders', blurb: 'Real code, real logic, real fun.', icon: 'code-2', tone: 'navy', level: 'Intermediate', levelColor: 'yellow', age: '10–13', lessons: 18, cat: 'Coding' },
        { title: 'Intro to AI & ML', blurb: 'Teach a computer to see and read.', icon: 'brain-circuit', tone: 'teal', level: 'Intermediate', levelColor: 'orange', age: '12–15', lessons: 16, cat: 'AI' },
        { title: 'Robotics & Smart Devices', blurb: 'Make things move with code.', icon: 'bot', tone: 'yellow', level: 'Advanced', levelColor: 'navy', age: '13–18', lessons: 20, cat: 'Robotics' },
      ],
    },
    how: {
      eyebrow: 'How it works',
      title: 'From first click to first project',
      steps: [
        { icon: 'mouse-pointer-click', bg: 'var(--gradient-warm)', title: 'Pick a track', body: "Choose a path that fits your child's age and curiosity — from Scratch games to AI." },
        { icon: 'users', bg: 'var(--gradient-ai)', title: 'Learn live, 1:1', body: 'Small live classes with a mentor who guides every step and celebrates every win.' },
        { icon: 'rocket', bg: 'var(--gradient-navy)', title: 'Ship a real project', body: 'Every track ends with a real game or app your child builds and proudly owns.' },
      ],
    },
    proof: {
      eyebrow: 'Loved by parents',
      title: 'Trusted by families, built for makers',
      sub: 'Real projects and real words from the parents who matter most.',
      quotes: [
        { text: 'My daughter went from playing games to building her own in six weeks. The mentors are incredible.', name: 'Sarah M.', role: 'Parent of Lina, 9', accent: 'var(--color-orange)' },
        { text: 'Finally, screen time I feel good about. He explains his code to us at dinner now!', name: 'Ahmed K.', role: 'Parent of Omar, 12', accent: 'var(--color-teal)' },
      ],
    },
    final: { title: 'FUTURE BEGINS HERE', sub: 'Book a free trial class and watch your child build their first project this week.', secondary: 'See pricing' },
    footer: {
      blurb: 'Online coding & AI academy preparing kids 8–18 to build the future — not just use it.',
      cols: [
        { h: 'Academy', links: ['Courses', 'How it works', 'Pricing', 'For schools'] },
        { h: 'Company', links: ['About us', 'Mentors', 'Careers', 'Contact'] },
        { h: 'Support', links: ['Help center', 'Parent guide', 'Safety', 'FAQ'] },
      ],
      rights: 'All rights reserved.',
    },
    modal: {
      kicker: 'Free · No commitment',
      title: 'Book a trial class',
      fParent: 'Parent name',
      pParent: 'e.g. Sarah',
      fEmail: 'Email',
      fChild: 'Child name',
      pChild: 'e.g. Lina',
      fAge: 'Child age',
      consent: 'Email me class details',
      submit: 'Book my free class',
      fine: 'We never share your data. Cancel anytime.',
      successTitle: "You're booked! 🎉",
      successBody: "We'll email your class details within 24 hours.",
      successCta: 'Done',
    },
  },
  ar: {
    nav: ['الكورسات', 'كيف نعمل', 'المشاريع', 'الأسعار'],
    cta: { book: 'احجز حصة مجانية', demo: 'شاهد العرض' },
    hero: {
      pill1: 'جديد',
      pill2: 'مسار الذكاء الاصطناعي',
      title: 'حيث تبني العقول الصغيرة',
      titleAccent: 'المستقبل',
      sub: 'حصص أونلاين مباشرة في البرمجة والذكاء الاصطناعي لعمر ٨–١٨ سنة، مع متابعة فردية — ليتخرّج كل طفل بمشروع حقيقي يملكه.',
      chips: ['من ٨ إلى ١٨ سنة', 'حصص مباشرة أونلاين', 'قائم على المشاريع'],
      floatNum: '+١٠٠٠',
      floatLabel: 'مشروع أنجزه الأطفال',
    },
    stats: [
      { v: '+١٢ ألف', l: 'صانع صغير' },
      { v: '+١٢٠', l: 'كورس مباشر' },
      { v: '٩٨٪', l: 'رضا الأهل' },
      { v: '٤٫٩★', l: 'متوسط التقييم' },
    ],
    courses: {
      eyebrow: 'المسارات الأكثر شعبية',
      title: 'كورسات يكملها الأطفال فعلاً',
      sub: 'مسارات قائمة على المشاريع تحوّل وقت الشاشة إلى وقت بناء.',
      filters: ['الكل', 'برمجة', 'ذكاء اصطناعي', 'روبوتات'],
      cta: 'عرض الكورس',
      items: [
        { title: 'تصميم الألعاب بـ Scratch', blurb: 'اسحب، أفلت، والعب — أول لعبة حقيقية.', icon: 'gamepad-2', tone: 'orange', level: 'مبتدئ', levelColor: 'teal', age: '٨–١٠', lessons: '١٢', cat: 'برمجة' },
        { title: 'بايثون للمبرمجين الصغار', blurb: 'كود حقيقي ومنطق ومتعة.', icon: 'code-2', tone: 'navy', level: 'متوسط', levelColor: 'yellow', age: '١٠–١٣', lessons: '١٨', cat: 'برمجة' },
        { title: 'مقدمة في الذكاء الاصطناعي', blurb: 'علّم الحاسوب أن يرى ويقرأ.', icon: 'brain-circuit', tone: 'teal', level: 'متوسط', levelColor: 'orange', age: '١٢–١٥', lessons: '١٦', cat: 'ذكاء اصطناعي' },
        { title: 'الروبوتات والأجهزة الذكية', blurb: 'حرّك الأشياء بالكود.', icon: 'bot', tone: 'yellow', level: 'متقدم', levelColor: 'navy', age: '١٣–١٨', lessons: '٢٠', cat: 'روبوتات' },
      ],
    },
    how: {
      eyebrow: 'كيف نعمل',
      title: 'من أول نقرة إلى أول مشروع',
      steps: [
        { icon: 'mouse-pointer-click', bg: 'var(--gradient-warm)', title: 'اختر مسارك', body: 'اختر المسار المناسب لعمر طفلك وفضوله — من ألعاب Scratch إلى الذكاء الاصطناعي.' },
        { icon: 'users', bg: 'var(--gradient-ai)', title: 'تعلّم مباشرة، فردي', body: 'حصص مباشرة صغيرة مع مدرّب يوجّه كل خطوة ويحتفل بكل إنجاز.' },
        { icon: 'rocket', bg: 'var(--gradient-navy)', title: 'أنجز مشروعاً حقيقياً', body: 'كل مسار ينتهي بلعبة أو تطبيق حقيقي يبنيه طفلك ويملكه بفخر.' },
      ],
    },
    proof: {
      eyebrow: 'يحبّه الأهل',
      title: 'ثقة العائلات، وصناعة للمبدعين',
      sub: 'مشاريع حقيقية وكلمات حقيقية من أولياء الأمور.',
      quotes: [
        { text: 'انتقلت ابنتي من اللعب إلى بناء ألعابها خلال ٦ أسابيع. المدرّبون رائعون.', name: 'سارة م.', role: 'والدة لينا، ٩ سنوات', accent: 'var(--color-orange)' },
        { text: 'أخيراً وقت شاشة أشعر بالرضا عنه. صار يشرح لنا الكود على العشاء!', name: 'أحمد ك.', role: 'والد عمر، ١٢ سنة', accent: 'var(--color-teal)' },
      ],
    },
    final: { title: 'المستقبل يبدأ من هنا', sub: 'احجز حصة تجريبية مجانية وشاهد طفلك يبني أول مشروع هذا الأسبوع.', secondary: 'شاهد الأسعار' },
    footer: {
      blurb: 'أكاديمية أونلاين للبرمجة والذكاء الاصطناعي تجهّز الأطفال ٨–١٨ لبناء المستقبل، لا استخدامه فقط.',
      cols: [
        { h: 'الأكاديمية', links: ['الكورسات', 'كيف نعمل', 'الأسعار', 'للمدارس'] },
        { h: 'الشركة', links: ['من نحن', 'المدرّبون', 'الوظائف', 'تواصل معنا'] },
        { h: 'الدعم', links: ['مركز المساعدة', 'دليل الأهل', 'الأمان', 'الأسئلة'] },
      ],
      rights: 'جميع الحقوق محفوظة.',
    },
    modal: {
      kicker: 'مجاناً · بدون التزام',
      title: 'احجز حصة تجريبية',
      fParent: 'اسم ولي الأمر',
      pParent: 'مثال: سارة',
      fEmail: 'البريد الإلكتروني',
      fChild: 'اسم الطفل',
      pChild: 'مثال: لينا',
      fAge: 'عمر الطفل',
      consent: 'أوافق على استلام تفاصيل الحصة',
      submit: 'احجز حصتي المجانية',
      fine: 'لن نشارك بياناتك. يمكنك الإلغاء في أي وقت.',
      successTitle: 'تم الحجز! 🎉',
      successBody: 'سنرسل تفاصيل الحصة عبر بريدك خلال ٢٤ ساعة.',
      successCta: 'تمام',
    },
  },
};
