import type { Copy, Lang } from './types';

export const COPY: Record<Lang, Copy> = {
  en: {
    nav: ['Courses', 'How it works', 'Projects', 'Pricing'],
    cta: { book: "Book your child's spot now", demo: 'Watch demo' },
    units: { ages: 'Ages', sessions: 'sessions', hours: 'hrs', currency: 'EGP' },
    hero: {
      pill1: 'New',
      pill2: 'AI track for teens',
      title: 'Where young minds build the',
      titleAccent: 'future',
      sub: 'Live, online coding & AI classes for ages 8–16 — taught with one-on-one guidance, so every child graduates owning a real project.',
      chips: ['Ages 8–16', 'Live online classes', 'Project-based'],
      floatNum: '108h',
      floatLabel: 'of hands-on training',
    },
    stats: [
      { v: '4', l: 'Learning tracks' },
      { v: '108', l: 'Training hours' },
      { v: '8–16', l: 'Ages' },
      { v: '100%', l: 'Project-based' },
    ],
    courses: {
      eyebrow: 'Academy tracks',
      title: 'A path from first block to AI',
      sub: 'Four progressive levels — each ends with a real graduation project your child owns.',
      filters: ['All', 'Coding', 'AI', 'Web'],
      cta: 'View details',
      syllabusLabel: "What you'll learn",
      items: [
        {
          id: 'scratch',
          title: 'Scratch',
          stack: 'Visual coding',
          blurb: 'Drag-and-drop coding — build a first real game.',
          icon: 'gamepad-2',
          image: '/assets/courses/scratch.png',
          tone: 'orange',
          level: 'Level 1',
          levelColor: 'teal',
          age: '8–10',
          sessions: 10,
          hours: 20,
          price: 1400,
          cat: 'Coding',
          syllabus: [
            'Intro to Scratch & the interface',
            'Motion & events',
            'Sounds & backdrops',
            'Variables',
            'Conditionals',
            'Loops',
            'Build a simple game',
            'Improve the game & add levels',
            'Final project',
            'Project showcase & review',
          ],
        },
        {
          id: 'app-inventor',
          title: 'App Inventor',
          stack: 'Mobile apps',
          blurb: 'Build real Android apps with visual blocks.',
          icon: 'smartphone',
          image: '/assets/courses/app-inventor.png',
          tone: 'navy',
          level: 'Level 2',
          levelColor: 'yellow',
          age: '10–14',
          sessions: 12,
          hours: 24,
          price: 1600,
          cat: 'Coding',
          syllabus: [
            'Intro to App Inventor',
            'Designing app interfaces',
            'Events & buttons',
            'Variables',
            'Multiple screens',
            'Images & media',
            'Simple databases',
            'Maps & location',
            'Calculator app',
            'To-Do List app',
            'Graduation project',
            'Project showcase',
          ],
        },
        {
          id: 'python-ai',
          title: 'Python + AI',
          stack: 'Python · Machine Learning',
          blurb: 'Real code, then teach a computer to learn.',
          icon: 'brain-circuit',
          image: '/assets/courses/python-ai.png',
          tone: 'teal',
          level: 'Level 3',
          levelColor: 'orange',
          age: '12–16',
          sessions: 16,
          hours: 32,
          price: 2400,
          cat: 'AI',
          syllabus: [
            'Python — Intro & your first program',
            'Variables & data types',
            'Arithmetic operations',
            'Conditionals',
            'Loops',
            'Functions',
            'Lists & dictionaries',
            'Strings',
            'Files',
            'Python project',
            'AI — Intro to Artificial Intelligence',
            'Machine Learning basics',
            'Data & training',
            'Using AI tools',
            'AI project',
            'Project showcase',
          ],
        },
        {
          id: 'web',
          title: 'Web Development',
          stack: 'HTML · CSS · JavaScript',
          blurb: 'Build and ship a real interactive website.',
          icon: 'code-2',
          image: '/assets/courses/web.png',
          tone: 'yellow',
          level: 'Level 4',
          levelColor: 'navy',
          age: '12–16',
          sessions: 16,
          hours: 32,
          price: 2400,
          cat: 'Web',
          syllabus: [
            'HTML — Intro & page structure',
            'Text, images & links',
            'Tables & forms',
            'CSS — basics',
            'Colors & fonts',
            'Flexbox',
            'Responsive design',
            'JavaScript — Intro',
            'Variables',
            'Conditionals',
            'Loops',
            'Functions',
            'DOM',
            'Events',
            'Interactive website project',
            'Graduation project',
          ],
        },
      ],
    },
    how: {
      eyebrow: 'How it works',
      title: 'From first click to first project',
      steps: [
        {
          icon: 'mouse-pointer-click',
          bg: 'var(--gradient-warm)',
          title: 'Pick a level',
          body: "Choose the track that fits your child's age — from Scratch games to AI and web.",
        },
        {
          icon: 'users',
          bg: 'var(--gradient-ai)',
          title: 'Learn live online',
          body: 'Live classes with a mentor who guides every step and follows up throughout the course.',
        },
        {
          icon: 'rocket',
          bg: 'var(--gradient-navy)',
          title: 'Ship a real project',
          body: 'Every level ends with a graduation project your child builds, owns, and presents.',
        },
      ],
    },
    projects: {
      eyebrow: 'Made by kids',
      title: 'Real projects, built by young makers',
      sub: 'Every level ends with something real — here are a few favorites.',
      items: [
        {
          title: 'Space Dodger Game',
          maker: 'Lina, 9',
          tag: 'Scratch',
          icon: 'gamepad-2',
          image: '/assets/projects/space-dodger.png',
          tone: 'orange',
        },
        {
          title: 'To-Do List App',
          maker: 'Omar, 12',
          tag: 'App Inventor',
          icon: 'smartphone',
          image: '/assets/projects/todo-app.png',
          tone: 'navy',
        },
        {
          title: 'Quiz App in Python',
          maker: 'Maya, 13',
          tag: 'Python',
          icon: 'code-2',
          image: '/assets/projects/quiz-python.png',
          tone: 'teal',
        },
        {
          title: 'Cat vs Dog Classifier',
          maker: 'Youssef, 15',
          tag: 'AI',
          icon: 'brain-circuit',
          image: '/assets/projects/cat-dog-classifier.png',
          tone: 'yellow',
        },
        {
          title: 'Personal Portfolio Site',
          maker: 'Hana, 14',
          tag: 'Web',
          icon: 'palette',
          image: '/assets/projects/portfolio-site.png',
          tone: 'orange',
        },
        {
          title: 'Calculator App',
          maker: 'Karim, 11',
          tag: 'App Inventor',
          icon: 'smartphone',
          image: '/assets/projects/calculator-app.png',
          tone: 'navy',
        },
      ],
    },
    pricing: {
      eyebrow: 'Bundles & pricing',
      title: 'Save more with a bundle',
      sub: 'Enroll in a single course, or pick a bundle and save. No contracts, cancel anytime.',
      separateLabel: 'Separate price',
      saveLabel: 'You save',
      popular: 'Most popular',
      bundles: [
        {
          id: 'beginners',
          name: 'Beginners',
          courses: 'Scratch + App Inventor',
          separate: 3000,
          price: 2700,
          icon: 'rocket',
        },
        {
          id: 'young-dev',
          name: 'Young Developer',
          courses: 'Python + AI + Web Development',
          separate: 4800,
          price: 4300,
          icon: 'zap',
          featured: true,
        },
        {
          id: 'comprehensive',
          name: 'Comprehensive',
          courses: 'Scratch + App Inventor + Python + AI + Web',
          separate: 7800,
          price: 5700,
          icon: 'crown',
        },
      ],
      featuresTitle: 'Every plan includes',
      features: [
        'Live online classes',
        'Hands-on projects in every level',
        'Mentor follow-up during the course',
        'A graduation project per level',
        'Certificate of completion',
        'A progressive path from coding basics to AI & web',
      ],
      totalLabel: 'Total training hours, full path',
      totalValue: '108',
    },
    proof: {
      eyebrow: 'Loved by parents',
      title: 'Trusted by families, built for makers',
      sub: 'Real projects and real words from the parents who matter most.',
      quotes: [
        {
          text: 'My daughter went from playing games to building her own in six weeks. The mentors are incredible.',
          name: 'Sarah M.',
          role: 'Parent of Lina, 9',
          accent: 'var(--color-orange)',
        },
        {
          text: 'Finally, screen time I feel good about. He explains his code to us at dinner now!',
          name: 'Ahmed K.',
          role: 'Parent of Omar, 12',
          accent: 'var(--color-teal)',
        },
      ],
    },
    final: {
      title: 'FUTURE BEGINS HERE',
      sub: 'Book a free trial class and watch your child build their first project this week.',
      secondary: 'See pricing',
    },
    footer: {
      blurb:
        'Online coding & AI academy preparing kids 8–16 to build the future — not just use it.',
      cols: [
        { h: 'Academy', links: ['Courses', 'How it works', 'Pricing', 'Projects'] },
        { h: 'Company', links: ['About us', 'Mentors', 'Careers', 'Contact'] },
        { h: 'Support', links: ['Help center', 'Parent guide', 'Safety', 'FAQ'] },
      ],
      rights: 'All rights reserved.',
    },
    modal: {
      kicker: 'Free · No commitment',
      title: 'Book a trial class',
      fParent: 'Parent name',
      pParent: 'e.g. Sarah',
      fEmail: 'Email',
      fChild: 'Child name',
      pChild: 'e.g. Lina',
      fAge: 'Child age',
      consent: 'Email me class details',
      submit: 'Book my free class',
      fine: 'We never share your data. Cancel anytime.',
      successTitle: "You're booked! 🎉",
      successBody: "We'll email your class details within 24 hours.",
      successCta: 'Done',
    },
  },
  ar: {
    nav: ['الكورسات', 'كيف نعمل', 'المشاريع', 'الأسعار'],
    cta: { book: 'احجز مكان لطفلك الآن', demo: 'شاهد العرض' },
    units: { ages: 'العمر', sessions: 'سيشن', hours: 'ساعة', currency: 'جنيه' },
    hero: {
      pill1: 'جديد',
      pill2: 'مسار الذكاء الاصطناعي',
      title: 'حيث تبني العقول الصغيرة',
      titleAccent: 'المستقبل',
      sub: 'حصص أونلاين مباشرة في البرمجة والذكاء الاصطناعي لعمر ٨–١٦ سنة، مع متابعة فردية — ليتخرّج كل طفل بمشروع حقيقي يملكه.',
      chips: ['من ٨ إلى ١٦ سنة', 'حصص مباشرة أونلاين', 'قائم على المشاريع'],
      floatNum: '١٠٨ ساعة',
      floatLabel: 'تدريب عملي',
    },
    stats: [
      { v: '٤', l: 'مسارات تعليمية' },
      { v: '١٠٨', l: 'ساعة تدريبية' },
      { v: '٨–١٦', l: 'الأعمار' },
      { v: '٪١٠٠', l: 'مشاريع عملية' },
    ],
    courses: {
      eyebrow: 'مسارات الأكاديمية',
      title: 'مسار من أول لبنة حتى الذكاء الاصطناعي',
      sub: 'أربعة مستويات متدرّجة — كل مستوى ينتهي بمشروع تخرّج حقيقي يملكه طفلك.',
      filters: ['الكل', 'برمجة', 'ذكاء اصطناعي', 'ويب'],
      cta: 'عرض التفاصيل',
      syllabusLabel: 'محتوى الكورس',
      items: [
        {
          id: 'scratch',
          title: 'Scratch',
          stack: 'برمجة مرئية',
          blurb: 'برمجة بالسحب والإفلات — أول لعبة حقيقية.',
          icon: 'gamepad-2',
          image: '/assets/courses/scratch.png',
          tone: 'orange',
          level: 'المستوى الأول',
          levelColor: 'teal',
          age: '٨–١٠',
          sessions: 10,
          hours: 20,
          price: 1400,
          cat: 'برمجة',
          syllabus: [
            'التعرف على Scratch والواجهة',
            'الحركة والأحداث',
            'الأصوات والخلفيات',
            'المتغيرات',
            'الجمل الشرطية',
            'التكرار Loops',
            'تصميم لعبة بسيطة',
            'تطوير اللعبة وإضافة مستويات',
            'مشروع نهائي',
            'عرض المشاريع ومراجعة',
          ],
        },
        {
          id: 'app-inventor',
          title: 'App Inventor',
          stack: 'تطبيقات موبايل',
          blurb: 'اصنع تطبيقات أندرويد حقيقية بالبلوكات.',
          icon: 'smartphone',
          image: '/assets/courses/app-inventor.png',
          tone: 'navy',
          level: 'المستوى الثاني',
          levelColor: 'yellow',
          age: '١٠–١٤',
          sessions: 12,
          hours: 24,
          price: 1600,
          cat: 'برمجة',
          syllabus: [
            'مقدمة في App Inventor',
            'تصميم واجهات التطبيقات',
            'الأحداث والأزرار',
            'المتغيرات',
            'الشاشات المتعددة',
            'الصور والوسائط',
            'قواعد البيانات البسيطة',
            'الخرائط والموقع',
            'تطبيق آلة حاسبة',
            'تطبيق To-Do List',
            'مشروع التخرج',
            'عرض المشاريع',
          ],
        },
        {
          id: 'python-ai',
          title: 'Python + AI',
          stack: 'بايثون · تعلّم الآلة',
          blurb: 'كود حقيقي، ثم علّم الحاسوب أن يتعلّم.',
          icon: 'brain-circuit',
          image: '/assets/courses/python-ai.png',
          tone: 'teal',
          level: 'المستوى الثالث',
          levelColor: 'orange',
          age: '١٢–١٦',
          sessions: 16,
          hours: 32,
          price: 2400,
          cat: 'ذكاء اصطناعي',
          syllabus: [
            'بايثون — مقدمة وبرمجة أول برنامج',
            'المتغيرات وأنواع البيانات',
            'العمليات الحسابية',
            'الشروط',
            'الحلقات',
            'الدوال',
            'القوائم والقواميس',
            'Strings',
            'الملفات',
            'مشروع Python',
            'الذكاء الاصطناعي — مقدمة',
            'أساسيات Machine Learning',
            'البيانات والتدريب',
            'استخدام أدوات AI',
            'مشروع AI',
            'عرض المشاريع',
          ],
        },
        {
          id: 'web',
          title: 'Web Development',
          stack: 'HTML · CSS · JavaScript',
          blurb: 'ابنِ وانشر موقعاً تفاعلياً حقيقياً.',
          icon: 'code-2',
          image: '/assets/courses/web.png',
          tone: 'yellow',
          level: 'المستوى الرابع',
          levelColor: 'navy',
          age: '١٢–١٦',
          sessions: 16,
          hours: 32,
          price: 2400,
          cat: 'ويب',
          syllabus: [
            'HTML — مقدمة وهيكل الصفحة',
            'النصوص والصور والروابط',
            'الجداول والفورمات',
            'CSS — الأساسيات',
            'الألوان والخطوط',
            'Flexbox',
            'Responsive Design',
            'JavaScript — مقدمة',
            'المتغيرات',
            'الشروط',
            'الحلقات',
            'الدوال',
            'DOM',
            'Events',
            'مشروع موقع تفاعلي',
            'مشروع التخرج',
          ],
        },
      ],
    },
    how: {
      eyebrow: 'كيف نعمل',
      title: 'من أول نقرة إلى أول مشروع',
      steps: [
        {
          icon: 'mouse-pointer-click',
          bg: 'var(--gradient-warm)',
          title: 'اختر المستوى',
          body: 'اختر المسار المناسب لعمر طفلك — من ألعاب Scratch إلى الذكاء الاصطناعي والويب.',
        },
        {
          icon: 'users',
          bg: 'var(--gradient-ai)',
          title: 'تعلّم مباشرة أونلاين',
          body: 'حصص مباشرة مع مدرّب يوجّه كل خطوة ويتابع طوال الكورس.',
        },
        {
          icon: 'rocket',
          bg: 'var(--gradient-navy)',
          title: 'أنجز مشروعاً حقيقياً',
          body: 'كل مستوى ينتهي بمشروع تخرّج يبنيه طفلك ويملكه ويعرضه بفخر.',
        },
      ],
    },
    projects: {
      eyebrow: 'صناعة الأطفال',
      title: 'مشاريع حقيقية صنعها صُنّاع صغار',
      sub: 'كل مستوى ينتهي بمشروع حقيقي — إليك بعض المفضّلة.',
      items: [
        {
          title: 'لعبة المركبة الفضائية',
          maker: 'لينا، ٩',
          tag: 'Scratch',
          icon: 'gamepad-2',
          image: '/assets/projects/space-dodger.png',
          tone: 'orange',
        },
        {
          title: 'تطبيق قائمة المهام',
          maker: 'عمر، ١٢',
          tag: 'App Inventor',
          icon: 'smartphone',
          image: '/assets/projects/todo-app.png',
          tone: 'navy',
        },
        {
          title: 'تطبيق اختبارات بـ بايثون',
          maker: 'مايا، ١٣',
          tag: 'Python',
          icon: 'code-2',
          image: '/assets/projects/quiz-python.png',
          tone: 'teal',
        },
        {
          title: 'مصنّف القطط والكلاب',
          maker: 'يوسف، ١٥',
          tag: 'ذكاء اصطناعي',
          icon: 'brain-circuit',
          image: '/assets/projects/cat-dog-classifier.png',
          tone: 'yellow',
        },
        {
          title: 'موقع بورتفوليو شخصي',
          maker: 'هنا، ١٤',
          tag: 'ويب',
          icon: 'palette',
          image: '/assets/projects/portfolio-site.png',
          tone: 'orange',
        },
        {
          title: 'تطبيق آلة حاسبة',
          maker: 'كريم، ١١',
          tag: 'App Inventor',
          icon: 'smartphone',
          image: '/assets/projects/calculator-app.png',
          tone: 'navy',
        },
      ],
    },
    pricing: {
      eyebrow: 'الباقات والأسعار',
      title: 'وفّر أكثر مع الباقات',
      sub: 'اشترك في كورس واحد، أو اختر باقة ووفّر. بدون عقود، وألغِ في أي وقت.',
      separateLabel: 'السعر المنفصل',
      saveLabel: 'بتوفّر',
      popular: 'الأكثر شعبية',
      bundles: [
        {
          id: 'beginners',
          name: 'باقة المبتدئين',
          courses: 'Scratch + App Inventor',
          separate: 3000,
          price: 2700,
          icon: 'rocket',
        },
        {
          id: 'young-dev',
          name: 'باقة المطور الشاب',
          courses: 'Python + AI + Web Development',
          separate: 4800,
          price: 4300,
          icon: 'zap',
          featured: true,
        },
        {
          id: 'comprehensive',
          name: 'الباقة الشاملة',
          courses: 'Scratch + App Inventor + Python + AI + Web',
          separate: 7800,
          price: 5700,
          icon: 'crown',
        },
      ],
      featuresTitle: 'كل الباقات تشمل',
      features: [
        'الدراسة أونلاين مباشرة',
        'مشاريع عملية في كل مستوى',
        'متابعة من المدرّب أثناء الكورس',
        'مشروع تخرّج لكل مستوى',
        'شهادة إتمام',
        'مسار تدريجي من أساسيات البرمجة حتى الذكاء الاصطناعي والويب',
      ],
      totalLabel: 'إجمالي ساعات المسار الكامل',
      totalValue: '١٠٨',
    },
    proof: {
      eyebrow: 'يحبّه الأهل',
      title: 'ثقة العائلات، وصناعة للمبدعين',
      sub: 'مشاريع حقيقية وكلمات حقيقية من أولياء الأمور.',
      quotes: [
        {
          text: 'انتقلت ابنتي من اللعب إلى بناء ألعابها خلال ٦ أسابيع. المدرّبون رائعون.',
          name: 'سارة م.',
          role: 'والدة لينا، ٩ سنوات',
          accent: 'var(--color-orange)',
        },
        {
          text: 'أخيراً وقت شاشة أشعر بالرضا عنه. صار يشرح لنا الكود على العشاء!',
          name: 'أحمد ك.',
          role: 'والد عمر، ١٢ سنة',
          accent: 'var(--color-teal)',
        },
      ],
    },
    final: {
      title: 'المستقبل يبدأ من هنا',
      sub: 'احجز حصة تجريبية مجانية وشاهد طفلك يبني أول مشروع هذا الأسبوع.',
      secondary: 'شاهد الأسعار',
    },
    footer: {
      blurb:
        'أكاديمية أونلاين للبرمجة والذكاء الاصطناعي تجهّز الأطفال ٨–١٦ لبناء المستقبل، لا استخدامه فقط.',
      cols: [
        { h: 'الأكاديمية', links: ['الكورسات', 'كيف نعمل', 'الأسعار', 'المشاريع'] },
        { h: 'الشركة', links: ['من نحن', 'المدرّبون', 'الوظائف', 'تواصل معنا'] },
        { h: 'الدعم', links: ['مركز المساعدة', 'دليل الأهل', 'الأمان', 'الأسئلة'] },
      ],
      rights: 'جميع الحقوق محفوظة.',
    },
    modal: {
      kicker: 'مجاناً · بدون التزام',
      title: 'احجز حصة تجريبية',
      fParent: 'اسم ولي الأمر',
      pParent: 'مثال: سارة',
      fEmail: 'البريد الإلكتروني',
      fChild: 'اسم الطفل',
      pChild: 'مثال: لينا',
      fAge: 'عمر الطفل',
      consent: 'أوافق على استلام تفاصيل الحصة',
      submit: 'احجز حصتي المجانية',
      fine: 'لن نشارك بياناتك. يمكنك الإلغاء في أي وقت.',
      successTitle: 'تم الحجز! 🎉',
      successBody: 'سنرسل تفاصيل الحصة عبر بريدك خلال ٢٤ ساعة.',
      successCta: 'تمام',
    },
  },
};
